name: Minikube workflow
on: push
jobs:
  minikube:
    name: Start Kubernetes cluster
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Start Minikube
        id: minikube
        uses: hiberbee/github-action-minikube@latest
        with:
          profile: github
                 
      - name: Deploy manifests
        run: |
          kubectl apply -f manifests/deploy.yaml
          kubectl apply -f manifests/service.yaml
          kubectl apply -f manifests/components.yaml
          kubectl apply -f manifests/hpa.yaml
        working-directory: ${{ github.workspace }}

      - name: Espera 30 segundos
        run: sleep 30

        #da tiempo a los pods de que corran.
        
      - name: Get All Info
        run: kubectl get all 
        #Se verifican los recursos en kubernetes donde 
        #además se podrá verificar el estado del HPA.
          
      - name: Get Minikube status
        run: minikube status

      - name: Get Test Service URLs
        run: minikube service list
